### ISSUE TITLE
Transition the cron job calling from my account to a future account

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#12]
Cron jobs is being used to cause an http request every 30mins to move current events that are over to past events:

https://cron-job.org/en/members/

**Comment by fstonedahl** [comment]
Could we use Cloud Scheduler for this instead?

https://firebase.googleblog.com/2019/04/schedule-cloud-functions-firebase-cron.html

**Comment by kyleworkman15** [comment]
I looked at that before and that would probably work. When I had first read up on that, I thought it cost for each use but it looks like it's free?

**Comment by fstonedahl** [comment]
Michael -- did you confirm that this is working using the new system now?

One more thought:  maybe we want to always give events 30-60 minutes of extra time in "current events" before moving into past events, because if OSL people do the raffles at the end, it would be bad for them if the event runs a little long, and they can't find the current event to run the raffle anymore!

This doesn't mean running the cron job less frequently, just that we should change the comparison within the cron job to give it a buffer of startTime + duration + 30 (or 60?).

**Comment by mwardach** [comment]
Done. (duration + 60 mins)
