### ISSUE TITLE
Display all events at once on start up

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#36]

**Comment by fstonedahl** [comment]
Loading was much slower over DATA than over web.  This is likely related to the issue of downloading a bunch of images.  Is this better now that we're using smaller thumbnails?  
Quite possibly we should reduce thumbnail size further, to save data usage?  (maybe 300x300?)

This issue is also closely related to issue #37 .

Note: we don't want to display *all* events... just for the upcoming week, until they scroll for more?

**Comment by fstonedahl** [comment]
This has become irrelevant, since we're planning to change the UI to show one week at a time.
