### ISSUE TITLE
On Demand Loading and Date Headings

### ISSUE THREAD

**Issue by mwardach** [augustanacsc490spring2019/OSL-Calendar-Web-App#37]
On Android use RecyclerView:
https://www.journaldev.com/24041/android-recyclerview-load-more-endless-scrolling
https://www.journaldev.com/12372/android-recyclerview-example

On iOS use UICollectionView:
https://developer.apple.com/documentation/uikit/uicollectionview

**Comment by fstonedahl** [comment]
**Change of direction:** I think we want to use one of the two RecyclerView user interface elements from "FirebaseUI".

Official docs: https://github.com/firebase/FirebaseUI-Android/tree/master/database

Here's one tutorial to check out, that loads images also.
https://www.coderefer.com/firebaseui-android-firebase-database/
Demo: https://www.youtube.com/watch?v=u8aeUOkhlpc

Here's a longer set of videos that looks like it may explain things in more detail, but is using the newer Firestore instead of our RealtimeDatabase.  I suspect the changes between the two database backends would be pretty small though.  (No images in this one though...)

https://www.youtube.com/watch?v=ub6mNHWGVHw

**Comment by fstonedahl** [comment]
Current thought:
* Add "Prev Week" / "Next Week" navigation mechanism
* A RecyclerView (but not FirebaseRecyclerView, since that can't filter for us) will only show events for the active week
* Download ALL current-events from firebase when the events list screen first loads, and handle all filtering/querying locally.  (Create an `allEvents` list, and then use that to create a `displayEventsList` that contains only the right date range and only the events that the user should see.)
* We should not download images until users are viewing the week that contains that item. (That should happen normally as long as we only do the image loading when the view gets bound to the viewholder)

**Comment by mwardach** [comment]
Done.
